# Generated by Django 5.0.1 on 2024-03-20 16:41

import authentication.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre')),
                ('token_email_validation', models.CharField(default='', max_length=100, verbose_name='Token para validar correo')),
                ('token_password_reset', models.CharField(default='', max_length=100, verbose_name='Token para reiniciar password')),
                ('token_expiration', models.DateTimeField(null=True, verbose_name='Fecha valida para token')),
                ('public_key', models.CharField(default='', max_length=100, verbose_name='Public key')),
                ('private_key', models.CharField(default='', max_length=100, verbose_name='Private key')),
                ('phone_number', models.CharField(default='', max_length=25, verbose_name='Número de teléfono')),
                ('receive_emails', models.BooleanField(default=True, verbose_name='Recibir correos electrónicos')),
                ('groups', models.ManyToManyField(related_name='users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
