# Generated by Django 5.0.1 on 2024-03-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_two_factor_auth_key_user_two_factor_auth_method_and_more'),
        ('company', '0002_company_historicalcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(related_name='user_company', to='company.company', verbose_name='Empresa'),
        ),
    ]
