# Generated by Django 5.0.1 on 2024-03-23 17:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_steps', models.IntegerField(default=0, verbose_name='Pasos de creacion de cuenta')),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('collaborator_can_create_invoice', models.BooleanField(default=False)),
                ('receive_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('legal_business_name', models.CharField(max_length=150, verbose_name='Razón social')),
                ('commercial_name', models.CharField(max_length=150, verbose_name='Nombre comercial')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='Nit')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('website', models.CharField(default='', max_length=25, verbose_name='Página web')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('description', models.CharField(max_length=700, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('register_steps', models.IntegerField(default=0, verbose_name='Pasos de creacion de cuenta')),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('collaborator_can_create_invoice', models.BooleanField(default=False)),
                ('receive_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('legal_business_name', models.CharField(max_length=150, verbose_name='Razón social')),
                ('commercial_name', models.CharField(max_length=150, verbose_name='Nombre comercial')),
                ('nit', models.CharField(db_index=True, max_length=30, verbose_name='Nit')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('website', models.CharField(default='', max_length=25, verbose_name='Página web')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('description', models.CharField(max_length=700, null=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'historical Empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
